### ISSUE TITLE
support for vip_port_id 

### ISSUE THREAD

**Issue by kucerakk** [opentelekomcloud-infra/octavia-proxy#62]
https://github.com/opentelekomcloud-infra/octavia-proxy/blob/f9e3d6b7db3e08a5748c41e64b15e99fbb86d956/octavia_proxy/api/v2/controllers/load_balancer.py#L183

Don't we want to support vip_port_id ? Or this will be as non-supported ? 

```
if CONF.networking.allow_vip_port_id:
  allowed_network_objects.append('vip_port_id')
```

**Comment by gtema** [comment]
we can not really support this that easy, only as a dirty fix

**Comment by kucerakk** [comment]
N/A
